### ISSUE TITLE
explain purpose/value of separate train, query, and ref datasets

### ISSUE THREAD

**Issue by alanngnet** [alanngnet/CoverHunterMPS#3]
Explain in the README and/or in code comments why the default configuration of CoverHunter was to set all of these hyperparameters to point to the same dataset:
```
# Data parameters
train_path: "data/covers80/full.txt"
train_sample_path: "data/covers80/full.txt"
dev_path: "data/covers80/full.txt"

covers80:
  query_path: "data/covers80/full.txt"
  ref_path: "data/covers80/full.txt"
  every_n_epoch_to_dev: 1 # validate after every n epoch
```
  
If this is a useful configuration, then how is its utility different than specifying different datasets for each hyperparameter?
How is specifying the same dataset for all phases of training supposed to succeed?
